### ISSUE TITLE
DNS-SD crashes DNS Client service on Windows 10 14393+ PC, Xbox, etc.

### ISSUE THREAD

**Issue by riverar** [Microsoft/Windows-appsample-networkhelper#6] opened 2016-09-17 09:01 UTC
Upon adding entries to the service's TextAttributes, DNS Client service in Windows crashes.
Demo project and additional tracking on User Voice: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/16010314-dns-sd-api-crashes-dns-client-service-on-windows-1

**Comment by msatranjr** [comment] 2016-09-21 21:28
Closing this because it's a potential platform issue, not a sample issue. If there is a specific issue with this sample please fork the repo and provide detail of how to reproduce the issue. In the meantime, I'll forward your User-voice issue to the right people. Thanks for reaching out.

**Closed by msatranjr** 2016-09-21 21:28 UTC
